import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'fr' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    'nav.content': 'Contenu',
    'nav.benefits': 'Avantages',
    'nav.testimonials': 'Témoignages',
    'nav.start': 'Commencer',
    'nav.back': 'Retour',
    'hero.badge': 'Nouveau 🇹🇳',
    'hero.title': 'Prépare ton Bac 2026 avec confiance',
    'hero.subtitle': 'Cours, séries, extraits et corrigés — tout dans un seul pack.',
    'hero.cta': 'Découvre le pack',
    'hero.students': 'Élèves actifs',
    'hero.satisfaction': 'Satisfaction',
    'hero.success': 'Succès garanti',
    'hero.successSub': 'Avec nos méthodes',
    'features.title': 'Qu\'est-ce qui est inclus dans le pack ?',
    'features.subtitle': 'Tout ce dont tu as besoin pour réussir ton Bac',
    'features.courses': 'Cours',
    'features.coursesDesc': 'Cours complets et structurés selon le programme officiel',
    'features.exercises': 'Exercices & Séries',
    'features.exercisesDesc': 'Des centaines d\'exercices avec différents niveaux',
    'features.extracts': 'Extraits Bac',
    'features.extractsDesc': 'Vrais sujets d\'examens des années précédentes',
    'features.extracurricular': 'Parascolaires',
    'features.extracurricularDesc': 'Supports complémentaires pour approfondir',
    'features.corrections': 'Corrigés',
    'features.correctionsDesc': 'Corrections détaillées pour tous les exercices',
    'benefits.title': 'Pourquoi choisir Bac Pack 2026 ?',
    'benefits.subtitle': 'La meilleure préparation pour ton Bac',
    'benefits.verified': 'Contenu vérifié par des enseignants',
    'benefits.adapted': '100% adapté au programme tunisien',
    'benefits.updates': 'Mises à jour gratuites',
    'benefits.mobile': 'Accessible sur mobile',
    'testimonials.title': 'Ils nous font confiance',
    'testimonials.amira': 'Grâce à Bac Pack, j\'ai réussi mon Bac avec mention. Les corrigés sont très détaillés !',
    'testimonials.amiraName': 'Amira K.',
    'testimonials.amiraTitle': 'Bac 2025',
    'testimonials.mohamed': 'Les séries d\'exercices m\'ont beaucoup aidé à comprendre les mathématiques. Je recommande !',
    'testimonials.mohamedName': 'Mohamed S.',
    'testimonials.mohamedTitle': 'Bac 2025',
    'testimonials.salma': 'Parfait pour réviser partout ! J\'utilise le pack sur mon téléphone pendant le trajet.',
    'testimonials.salmaName': 'Salma B.',
    'testimonials.salmaTitle': 'Élève actuelle',
    'testimonials.studentsCount': '+2000 élèves',
    'testimonials.trust': 'nous font confiance chaque année',
    'cta.title': 'Prêt à réussir ton Bac 2026 ?',
    'cta.subtitle': 'Rejoins des milliers d\'élèves qui préparent leur succès avec Bac Pack',
    'cta.download': 'Télécharger le pack maintenant',
    'cta.start': 'Commence ta révision aujourd\'hui',
    'footer.tagline': 'Votre partenaire de confiance pour réussir le Bac en Tunisie.',
    'footer.contact': 'Contact',
    'footer.email': 'Email: contact@bacpack2026.tn',
    'footer.phone': 'Tél: +216 XX XXX XXX',
    'footer.follow': 'Suivez-nous',
    'footer.rights': '© 2026 Bac Pack. Tous droits réservés.',
    'selection.title': 'Personnalise ton pack',
    'selection.subtitle': 'Sélectionne ta spécialité et ta matière optionnelle',
    'selection.bacTitle': 'Choisis ton type de Bac',
    'selection.optionalTitle': 'Choisis ta matière optionnelle',
    'selection.submit': 'Télécharger mon pack personnalisé',
    'selection.warning': 'Veuillez sélectionner votre spécialité et votre matière optionnelle',
    'bac.math': 'BAC MATHEMATIQUE',
    'bac.sciences': 'BAC SCIENCES EXPERIMENTALES',
    'bac.letters': 'BAC LETTRES',
    'bac.info': 'BAC INFORMATIQUE',
    'bac.tech': 'BAC TECHNIQUE',
    'bac.econ': 'BAC ECONOMIE ET GESTION',
    'optional.spanish': 'ESPAGNOL',
    'optional.italian': 'ITALIEN',
    'optional.german': 'ALLEMAND',
    'pack.title': 'Votre Pack Personnalisé',
    'pack.limited': 'Offre Spéciale',
    'pack.whatIncluded': 'Ce qui est inclus',
    'pack.complete': 'Cours complets adaptés à votre spécialité',
    'pack.exercises': 'Centaines d\'exercices avec corrigés détaillés',
    'pack.exams': 'Vrais sujets d\'examens du Bac',
    'pack.corrections': 'Solutions et explications',
    'pack.lifetime': 'Accès à vie sans frais supplémentaires',
    'pack.selected': 'Votre sélection',
    'pack.specialty': 'Spécialité',
    'pack.optional': 'Matière optionnelle',
    'pack.deliveryInfo': 'Informations de Livraison',
    'pack.fullName': 'Nom Complet',
    'pack.fullNamePlaceholder': 'Votre nom complet',
    'pack.email': 'Email',
    'pack.phone': 'Téléphone',
    'pack.address': 'Adresse',
    'pack.addressPlaceholder': 'Rue, numéro et bâtiment',
    'pack.city': 'Ville',
    'pack.cityPlaceholder': 'Tunis',
    'pack.postalCode': 'Code Postal',
    'pack.subtotal': 'Sous-total',
    'pack.shipping': 'Livraison',
    'pack.free': 'Gratuite',
    'pack.total': 'Total',
    'pack.confirmBuy': 'Confirmer l\'achat',
    'pack.fillAllFields': 'Veuillez remplir tous les champs',
    'pack.orderConfirmed': 'Commande confirmée!'
  },
  ar: {
    'nav.content': 'المحتوى',
    'nav.benefits': 'الفوايد',
    'nav.testimonials': 'شهادات',
    'nav.start': 'إبدا',
    'nav.back': 'رجوع',
    'hero.badge': 'جديد 🇹🇳',
    'hero.title': 'حضّر Bac 2026 متاعك بثقة',
    'hero.subtitle': 'Cours، سلسلات، مواضيع و Corrigés — الكل في Pack واحد.',
    'hero.cta': 'إكتشف الPack',
    'hero.students': 'تلميذ نشيط',
    'hero.satisfaction': 'رضا',
    'hero.success': 'نجاح مضمون',
    'hero.successSub': 'بطرقنا',
    'features.title': 'شنوا موجود في الPack؟',
    'features.subtitle': 'كل شي تحتاجو باش تنجح في الBac',
    'features.courses': 'Cours',
    'features.coursesDesc': 'Cours كاملة و مرتبة على حسب البرنامج',
    'features.exercises': 'Exercices و Séries',
    'features.exercisesDesc': 'مئات التمارين بمستويات مختلفة',
    'features.extracts': 'مواضيع الBac',
    'features.extractsDesc': 'مواضيع حقيقية من إمتحانات السنين اللي فاتت',
    'features.extracurricular': 'Parascolaires',
    'features.extracurricularDesc': 'حاجات زايدة باش تفهم أكثر',
    'features.corrections': 'Corrigés',
    'features.correctionsDesc': 'Corrigés détaillées لكل التمارين',
    'benefits.title': 'علاش تختار Pack Bac 2026؟',
    'benefits.subtitle': 'أحسن حاجة باش تحضر للBac',
    'benefits.verified': 'Contenu vérifié من عند المعلمين',
    'benefits.adapted': '100٪ adapté au programme tunisien',
    'benefits.updates': 'Mises à jour gratuites',
    'benefits.mobile': 'Accessible sur mobile',
    'testimonials.title': 'يثقو فينا',
    'testimonials.amira': 'Grâce au Pack Bac، نجحت في الBac بعلامة مليحة. الإصلاح مفصل برشا!',
    'testimonials.amiraName': 'أميرة ك.',
    'testimonials.amiraTitle': 'Bac 2025',
    'testimonials.mohamed': 'Séries d\'exercices عاونوني برشا نفهم الماطماطيك. ننصح بيهم!',
    'testimonials.mohamedName': 'محمد س.',
    'testimonials.mohamedTitle': 'Bac 2025',
    'testimonials.salma': 'Parfait pour réviser في أي بلاصة! نستعمل الPack من التليفون وقت نكون في الطريق.',
    'testimonials.salmaName': 'سلمى ب.',
    'testimonials.salmaTitle': 'Élève actuelle',
    'testimonials.studentsCount': '+2000 élèves',
    'testimonials.trust': 'nous font confiance كل عام',
    'cta.title': 'وليت جاهز تنجح في الBac 2026؟',
    'cta.subtitle': 'Rejoins des milliers d\'élèves اللي يحضرو للنجاح متاعهم مع Pack Bac',
    'cta.download': 'Télécharger le Pack maintenant',
    'cta.start': 'إبدا قرايتك اليوم',
    'footer.tagline': 'شريكك اللي تثق فيه باش تنجح في الBac في تونس.',
    'footer.contact': 'Contact',
    'footer.email': 'Email: contact@bacpack2026.tn',
    'footer.phone': 'Tél: +216 XX XXX XXX',
    'footer.follow': 'Suivez-nous',
    'footer.rights': '© 2026 Pack Bac. كل الحقوق محفوظة.',
    'selection.title': 'Personnalise ton Pack',
    'selection.subtitle': 'إختار التخصص متاعك و الماتيار الإختياري',
    'selection.bacTitle': 'Choisis ton type de Bac',
    'selection.optionalTitle': 'Choisis ta matière optionnelle',
    'selection.submit': 'Télécharger mon Pack personnalisé',
    'selection.warning': 'لازم تختار التخصص و الماتيار الإختياري',
    'bac.math': 'BAC MATHEMATIQUE',
    'bac.sciences': 'BAC SCIENCES EXPERIMENTALES',
    'bac.letters': 'BAC LETTRES',
    'bac.info': 'BAC INFORMATIQUE',
    'bac.tech': 'BAC TECHNIQUE',
    'bac.econ': 'BAC ECONOMIE ET GESTION',
    'optional.spanish': 'ESPAGNOL',
    'optional.italian': 'ITALIEN',
    'optional.german': 'ALLEMAND',
    'pack.title': 'Votre Pack Personnalisé',
    'pack.limited': 'Offre Spéciale',
    'pack.whatIncluded': 'Ce qui est inclus',
    'pack.complete': 'Cours complets adaptés à votre spécialité',
    'pack.exercises': 'Centaines d\'Exercices avec Corrigés détaillés',
    'pack.exams': 'Vrais sujets d\'examens du Bac',
    'pack.corrections': 'Solutions et Explications',
    'pack.lifetime': 'تنجم تستعملو على طول بلا مصاريف زايدة',
    'pack.selected': 'الإختيار متاعك',
    'pack.specialty': 'التخصص',
    'pack.optional': 'الماتيار الإختياري',
    'pack.deliveryInfo': 'معلومات التوصيل',
    'pack.fullName': 'الإسم الكامل',
    'pack.fullNamePlaceholder': 'إسمك الكامل',
    'pack.email': 'إيمايل',
    'pack.phone': 'نومرو تليفون',
    'pack.address': 'العنوان',
    'pack.addressPlaceholder': 'الشارع و النومرو و البناية',
    'pack.city': 'المدينة',
    'pack.cityPlaceholder': 'تونس',
    'pack.postalCode': 'الكود البوستال',
    'pack.subtotal': 'المجموع',
    'pack.shipping': 'التوصيل',
    'pack.free': 'بلاش',
    'pack.total': 'التوتال',
    'pack.confirmBuy': 'كونفيرمي الشراء',
    'pack.fillAllFields': 'لازم تعمر الكل',
    'pack.orderConfirmed': 'الكوموند تكونفرما!'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['fr']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
