import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'fr' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    'nav.content': 'Contenu',
    'nav.benefits': 'Avantages',
    'nav.testimonials': 'Témoignages',
    'nav.start': 'Commencer',
    'nav.back': 'Retour',
    'hero.badge': 'Nouveau 🇹🇳',
    'hero.title': 'Prépare ton Bac 2026 avec confiance',
    'hero.subtitle': 'Cours, séries, extraits et corrigés — tout dans un seul pack.',
    'hero.cta': 'Découvre le pack',
    'hero.students': 'Élèves actifs',
    'hero.satisfaction': 'Satisfaction',
    'hero.success': 'Succès garanti',
    'hero.successSub': 'Avec nos méthodes',
    'features.title': 'Qu\'est-ce qui est inclus dans le pack ?',
    'features.subtitle': 'Tout ce dont tu as besoin pour réussir ton Bac',
    'features.courses': 'Cours',
    'features.coursesDesc': 'Cours complets et structurés selon le programme officiel',
    'features.exercises': 'Exercices & Séries',
    'features.exercisesDesc': 'Des centaines d\'exercices avec différents niveaux',
    'features.extracts': 'Extraits Bac',
    'features.extractsDesc': 'Vrais sujets d\'examens des années précédentes',
    'features.extracurricular': 'Parascolaires',
    'features.extracurricularDesc': 'Supports complémentaires pour approfondir',
    'features.corrections': 'Corrigés',
    'features.correctionsDesc': 'Corrections détaillées pour tous les exercices',
    'benefits.title': 'Pourquoi choisir Bac Pack 2026 ?',
    'benefits.subtitle': 'La meilleure préparation pour ton Bac',
    'benefits.verified': 'Contenu vérifié par des enseignants',
    'benefits.adapted': '100% adapté au programme tunisien',
    'benefits.updates': 'Mises à jour gratuites',
    'benefits.mobile': 'Accessible sur mobile',
    'testimonials.title': 'Ils nous font confiance',
    'testimonials.amira': 'Grâce à Bac Pack, j\'ai réussi mon Bac avec mention. Les corrigés sont très détaillés !',
    'testimonials.amiraName': 'Amira K.',
    'testimonials.amiraTitle': 'Bac 2025',
    'testimonials.mohamed': 'Les séries d\'exercices m\'ont beaucoup aidé à comprendre les mathématiques. Je recommande !',
    'testimonials.mohamedName': 'Mohamed S.',
    'testimonials.mohamedTitle': 'Bac 2025',
    'testimonials.salma': 'Parfait pour réviser partout ! J\'utilise le pack sur mon téléphone pendant le trajet.',
    'testimonials.salmaName': 'Salma B.',
    'testimonials.salmaTitle': 'Élève actuelle',
    'testimonials.studentsCount': '+2000 élèves',
    'testimonials.trust': 'nous font confiance chaque année',
    'cta.title': 'Prêt à réussir ton Bac 2026 ?',
    'cta.subtitle': 'Rejoins des milliers d\'élèves qui préparent leur succès avec Bac Pack',
    'cta.download': 'Télécharger le pack maintenant',
    'cta.start': 'Commence ta révision aujourd\'hui',
    'footer.tagline': 'Votre partenaire de confiance pour réussir le Bac en Tunisie.',
    'footer.contact': 'Contact',
    'footer.email': 'Email: contact@bacpack2026.tn',
    'footer.phone': 'Tél: +216 XX XXX XXX',
    'footer.follow': 'Suivez-nous',
    'footer.rights': '© 2026 Bac Pack. Tous droits réservés.',
    'selection.title': 'Personnalise ton pack',
    'selection.subtitle': 'Sélectionne ta spécialité et ta matière optionnelle',
    'selection.bacTitle': 'Choisis ton type de Bac',
    'selection.optionalTitle': 'Choisis ta matière optionnelle',
    'selection.submit': 'Télécharger mon pack personnalisé',
    'selection.warning': 'Veuillez sélectionner votre spécialité et votre matière optionnelle',
    'bac.math': 'BAC MATHEMATIQUE',
    'bac.sciences': 'BAC SCIENCES EXPERIMENTALES',
    'bac.letters': 'BAC LETTRES',
    'bac.info': 'BAC INFORMATIQUE',
    'bac.tech': 'BAC TECHNIQUE',
    'bac.econ': 'BAC ECONOMIE ET GESTION',
    'optional.spanish': 'ESPAGNOL',
    'optional.italian': 'ITALIEN',
    'optional.german': 'ALLEMAND',
    'pack.title': 'Votre Pack Personnalisé',
    'pack.limited': 'Offre Spéciale',
    'pack.whatIncluded': 'Ce qui est inclus',
    'pack.complete': 'Cours complets adaptés à votre spécialité',
    'pack.exercises': 'Centaines d\'exercices avec corrigés détaillés',
    'pack.exams': 'Vrais sujets d\'examens du Bac',
    'pack.corrections': 'Solutions et explications',
    'pack.lifetime': 'Accès à vie sans frais supplémentaires',
    'pack.selected': 'Votre sélection',
    'pack.specialty': 'Spécialité',
    'pack.optional': 'Matière optionnelle',
    'pack.deliveryInfo': 'Informations de Livraison',
    'pack.fullName': 'Nom Complet',
    'pack.fullNamePlaceholder': 'Votre nom complet',
    'pack.email': 'Email',
    'pack.phone': 'Téléphone',
    'pack.address': 'Adresse',
    'pack.addressPlaceholder': 'Rue, numéro et bâtiment',
    'pack.city': 'Ville',
    'pack.cityPlaceholder': 'Tunis',
    'pack.postalCode': 'Code Postal',
    'pack.subtotal': 'Sous-total',
    'pack.shipping': 'Livraison',
    'pack.free': 'Gratuite',
    'pack.total': 'Total',
    'pack.confirmBuy': 'Confirmer l\'achat',
    'pack.fillAllFields': 'Veuillez remplir tous les champs',
    'pack.orderConfirmed': 'Commande confirmée!'
  },
  ar: {
    'nav.content': 'المحتوى',
    'nav.benefits': 'المزايا',
    'nav.testimonials': 'الشهادات',
    'nav.start': 'ابدأ',
    'nav.back': 'رجوع',
    'hero.badge': 'جديد 🇹🇳',
    'hero.title': 'حضّر للباكالوريا 2026 بثقة',
    'hero.subtitle': 'دروس، تمارين، مواضيع وحلول — كل شيء في حزمة واحدة.',
    'hero.cta': 'اكتشف الحزمة',
    'hero.students': 'تلميذ نشط',
    'hero.satisfaction': 'رضا',
    'hero.success': 'نجاح مضمون',
    'hero.successSub': 'بأساليبنا',
    'features.title': 'ماذا يتضمن الحزمة؟',
    'features.subtitle': 'كل ما تحتاجه للنجاح في الباكالوريا',
    'features.courses': 'الدروس',
    'features.coursesDesc': 'دروس كاملة ومنظمة حسب البرنامج الرسمي',
    'features.exercises': 'التمارين والسلاسل',
    'features.exercisesDesc': 'مئات التمارين بمستويات مختلفة',
    'features.extracts': 'مواضيع الباكالوريا',
    'features.extractsDesc': 'مواضيع حقيقية من امتحانات السنوات السابقة',
    'features.extracurricular': 'موارد إضافية',
    'features.extracurricularDesc': 'مواد تكميلية للتعمق أكثر',
    'features.corrections': 'الحلول',
    'features.correctionsDesc': 'تصحيحات مفصلة لجميع التمارين',
    'benefits.title': 'لماذا تختار حزمة الباكالوريا 2026؟',
    'benefits.subtitle': 'أفضل إعداد للباكالوريا الخاصة بك',
    'benefits.verified': 'محتوى تم التحقق منه من قبل المعلمين',
    'benefits.adapted': '100٪ متكيف مع البرنامج التونسي',
    'benefits.updates': 'تحديثات مجانية',
    'benefits.mobile': 'متاح على الهاتف المحمول',
    'testimonials.title': 'يثقون بنا',
    'testimonials.amira': 'بفضل حزمة الباكالوريا، نجحت في الباكالوريا بامتياز. الحلول مفصلة جداً!',
    'testimonials.amiraName': 'أميرة ك.',
    'testimonials.amiraTitle': 'باكالوريا 2025',
    'testimonials.mohamed': 'سلاسل التمارين ساعدتني كثيراً في فهم الرياضيات. أنصح بها!',
    'testimonials.mohamedName': 'محمد س.',
    'testimonials.mohamedTitle': 'باكالوريا 2025',
    'testimonials.salma': 'مثالي للمراجعة في كل مكان! أستخدم الحزمة على هاتفي أثناء التنقل.',
    'testimonials.salmaName': 'سلمى ب.',
    'testimonials.salmaTitle': 'تلميذة حالية',
    'testimonials.studentsCount': '+2000 تلميذ',
    'testimonials.trust': 'يثقون بنا كل عام',
    'cta.title': 'مستعد للنجاح في الباكالوريا 2026؟',
    'cta.subtitle': 'انضم إلى آلاف التلاميذ الذين يحضرون لنجاحهم مع حزمة الباكالوريا',
    'cta.download': 'حمّل الحزمة الآن',
    'cta.start': 'ابدأ مراجعتك اليوم',
    'footer.tagline': 'شريكك الموثوق للنجاح في الباكالوريا في تونس.',
    'footer.contact': 'اتصل بنا',
    'footer.email': 'البريد الإلكتروني: contact@bacpack2026.tn',
    'footer.phone': 'الهاتف: +216 XX XXX XXX',
    'footer.follow': 'تابعنا',
    'footer.rights': '© 2026 حزمة الباكالوريا. جميع الحقوق محفوظة.',
    'selection.title': 'خصص حزمتك',
    'selection.subtitle': 'اختر تخصصك والمادة الاختيارية',
    'selection.bacTitle': 'اختر نوع الباكالوريا',
    'selection.optionalTitle': 'اختر المادة الاختيارية',
    'selection.submit': 'حمّل حزمتي المخصصة',
    'selection.warning': 'يرجى اختيار تخصصك والمادة الاختيارية',
    'bac.math': 'باكالوريا رياضيات',
    'bac.sciences': 'باكالوريا علوم تجريبية',
    'bac.letters': 'باكالوريا آداب',
    'bac.info': 'باكالوريا إعلامية',
    'bac.tech': 'باكالوريا تقنية',
    'bac.econ': 'باكالوريا اقتصاد وتصرف',
    'optional.spanish': 'الإسبانية',
    'optional.italian': 'الإيطالية',
    'optional.german': 'الألمانية',
    'pack.title': 'حزمتك المخصصة',
    'pack.limited': 'عرض خاص',
    'pack.whatIncluded': 'ما هو مضمون',
    'pack.complete': 'دروس كاملة مكيفة مع تخصصك',
    'pack.exercises': 'مئات التمارين مع حلول مفصلة',
    'pack.exams': 'مواضيع حقيقية من امتحانات الباكالوريا',
    'pack.corrections': 'الحلول والشروحات',
    'pack.lifetime': 'وصول مدى الحياة بدون رسوم إضافية',
    'pack.selected': 'اختيارك',
    'pack.specialty': 'التخصص',
    'pack.optional': 'المادة الاختيارية',
    'pack.deliveryInfo': 'معلومات التسليم',
    'pack.fullName': 'الاسم الكامل',
    'pack.fullNamePlaceholder': 'اسمك الكامل',
    'pack.email': 'البريد الإلكتروني',
    'pack.phone': 'رقم الهاتف',
    'pack.address': 'العنوان',
    'pack.addressPlaceholder': 'الشارع والرقم والمبنى',
    'pack.city': 'المدينة',
    'pack.cityPlaceholder': 'تونس',
    'pack.postalCode': 'الرمز البريدي',
    'pack.subtotal': 'المجموع الفرعي',
    'pack.shipping': 'التسليم',
    'pack.free': 'مجاني',
    'pack.total': 'الإجمالي',
    'pack.confirmBuy': 'تأكيد الشراء',
    'pack.fillAllFields': 'يرجى ملء جميع الحقول',
    'pack.orderConfirmed': 'تم تأكيد الطلب!'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['fr']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
